[package]
name = "servo_media_derive"
version = "0.1.0"
authors = ["Fernando Jiménez Moreno <ferjmoreno@gmail.com>"]

[lib]
name = "servo_media_derive"
proc-macro = true
path = "lib.rs"

[dependencies]
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4"
